services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 88:80
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro

  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
      # - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      # - ./docker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf

  mysql:
    image: mysql:8.4
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-sandbox}"
      MYSQL_USER: "${DB_USERNAME:-sandboxer}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ROOT_PASSWORD: "root"
    restart: unless-stopped

  # backup:
  #   image: jkaninda/mysql-bkup
  #   command: backup --cron-expression "0 1 * * *" # каждый день в 1:00
  #   volumes:
  #     - ./docker/mysql/backups:/backup
  #   environment:
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_NAME=sandbox
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=root
  #   restart: unless-stopped

  # redis:
  #   image: 'redis:alpine'
  #   ports:
  #     - '${FORWARD_REDIS_PORT:-6379}:6379'
  #   volumes:
  #     - ./docker/redis:/data
  #   networks:
  #     - sandbox
  #   command: >
  #     sh -c " chown -R redis:redis /data && chmod -R 755 /data && redis-server --appendonly yes --stop-writes-on-bgsave-error no "
  #   healthcheck:
  #     test:
  #       - CMD
  #       - redis-cli
  #       - ping
  #     retries: 3
  #     timeout: 5s

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
    depends_on:
      - mysql
