services:
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway" # Для доступа к MySQL на хосте
    volumes:
      - ./:/var/www/app
      - vendor_volume:/var/www/app/vendor

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    networks:
      - app-network
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ADMINER_DEFAULT_SERVER=host.docker.internal
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  vendor_volume:
