services:
  app:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway" # Для доступа к MySQL на хосте
    volumes:
      - ./:/var/www/app

  nginx:
    image: nginx:stable-alpine
    ports:
      - 88:80
    networks:
      - app-network
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  adminer:
    image: adminer:latest
    network_mode: host # Оставляем для простоты
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306

networks:
  app-network:
    driver: bridge
