# -*- coding: utf-8 -*-
"""Копия блокнота "telegram_groups_parser_v2.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1177VUQxzRHqiadoKQWpMm7h36Rd_-ztf
"""

!pip install telethon
!pip install qrcode[pil]

from datetime import datetime, timezone
from telethon import TelegramClient
from google.colab import files
from google.colab import ai

import asyncio
import qrcode
import re

api_id = '###'
api_hash = '###'

channels = [
    "t.me/krasspeleo", # КККС - Новости
    "t.me/krashiking", # Красноярский Хайкинг
    # "t.me/krasalpchat/2713", # Красноярский клуб альпинистов
    "t.me/kraevushka_life", # Красноярская краевая научная библиотека
    "t.me/kolesimpokrau", # Visitsiberia
    "t.me/klubLarinaKrasnoyarsk", # Экскурсии, походы «Пути и Шествия» I 🧡 Турагенство Красноярск!
    "t.me/julia_stefanovskaja", # Точка Движения
    # "t.me/izitour_ru", # IZITOUR.RU ПОХОДЫ
    # "t.me/hodinazdorove", # ХОДИ НА ЗДОРОВЬЕ💚
    # "t.me/hardtorest", # турклуб «Отдыхать трудно»|туризм, походы в Красноярске
    # "t.me/gremgriva", # Эко-парк «Гремячая грива»
    # "t.me/fototestdrive", # ОЛЕСАЙКА
    # "t.me/familyclub_vmeste", # 👨‍👩‍👧‍👦ВМЕСТЕ👨‍👩‍👧‍👦 Семейный клуб
    # "t.me/expertvisitsiberia", # Эксперт.VisitSiberia 💙
    # "t.me/excursion24", # 🌐 Экскурсии Красноярск
    # "t.me/erebor24", # Ходим в горы 🙌🏻🏔👩‍👧‍👦
    # "t.me/endeavour_channel", # Endeavour Tour | Эндевор Тур
    # "t.me/elenaracprekrasnaya", # С РЮКЗАЧКОМ НАЛЕГКЕ!
    # "t.me/elenabogoslivets", # Гулять Так Гулять
    # "t.me/dvizhzh", # Анонсы походов
    # "t.me/dvizh_turizm", # ДВИЖЖЖ
    # "t.me/duh_nomad", # Дух Кочевника • Туры на снегоходах в Красноярске • Сплавы по Мане и Енисею • SUP • Байдарки • Морские каяки • Пакрафты • Квизы
    # "t.me/doska_sup_club", # Doska SUP club прогулки Красноярск
    # "t.me/domik_v_lesy_berloga", # Анонс будущих живых встреч
    # "t.me/doidykogdadoidy", # Дойду когда дойду
    # "t.me/clubalga24", # Анонсы ПВД (однодневных походов)
    # "t.me/city_guide", # Гид в нетуристическом городе
    # "t.me/bvs_trips", # Быстрее! Выше! Сильнее! 💪
    # "t.me/bobrolog", # Фанпарк «Бобровый лог»
    # "t.me/bigtravel365", # Big Travel
    # "t.me/bazaar_moms", # Mom’s Bazaar Афиша Красноярск
    # "t.me/artsupru", # АНОНСЫ ТУРОВ
    # "t.me/archeotour19", # Археотур. Путешествия по Хакасии
    # "t.me/YaraLi_tur", # ЯраЛи_тур 🧑‍💼👩‍💻
    # "t.me/TripBazaar_Travel", # TripBazaar 🌅 - МАРКЕТПЛЕЙС Путешествий /Событий/ Услуг в КРАСНОЯРСКЕ и ОКРЕСТНОСТЯХ.🌎🌏🌍
    # "t.me/SunTpona", # ☀️ SunTpoпa ☀️
    # "t.me/SUP_LINER_Mana", # SUP_LINER Туры по Мане, САП Красноярск
    # "t.me/R1MTBB2xIYRkN2Ri", # Активные Выходные_365
    # "t.me/Nina_baykalova", # Время с пользой
    # "t.me/NaXxNcuJfI1iZDEy", # Жанна Travel
    # "t.me/Manasup_ko", # Cапы с Мари Андре
    # "t.me/Kraj_Sayan", # По Краю Саян
    # "t.me/Kayaktrips", # Клуб Стихия⛷🏕✈️🚗🛶
    # "t.me/Hochu_I_Hozhu", # Хочу и хожу
    # "t.me/GeographyHiking", # 🌍 География 🌍 Походы
    # "t.me/ElenaDobroxodz", # Идём с нами)
    # "t.me/Back_Pack_Travel", # Бэк Пэк Тревел
    # "t.me/Active_Weekend365", # Активные выходные_365
    # "t.me/zamanie_tur", # zamanie_tur
    "t.me/airsiberia",
    "t.me/krassea_alliance", # KRASSEA ALLIANCE | ЯХТ ТУРЫ СО СМЫСЛОМ
    "t.me/shirnind",
    "t.me/supturkrsk",
    # 't.me/clubalga24/3', # Анонсы ПВД (однодневных походов) # (чат)
    "t.me/photo_trips",  # Фотопоходы- Тропами предков! 👣
    "t.me/mo_tour",  # Своя тропа * Походы * Путешествия * Приключения
    "t.me/geoturizm",  # Геотуризм - походы и экскурсии Красноярск
    "t.me/mystolby",  # Мои Столбы
    "t.me/na_opyte_tur",  # На опыте! Cнаряжение и туризм. Акции, скидки, рекомендации.
    "t.me/umberi_travel",  # Клуб путешественников УмБери 🌏
]

client = TelegramClient('getContent', api_id, api_hash)

async def main():

    # установка соединения
    await client.connect()

    #  авторизация
    if not await client.is_user_authorized():
        print("Генерируем QR-код...")
        qr_login = await client.qr_login()

        qr = qrcode.QRCode()
        qr.add_data(qr_login.url)
        img = qr.make_image()
        img.save('qr_code.png')

        files.download('qr_code.png')
        print("QR-код скачан. Отсканируйте его в Telegram")

        try:
            await qr_login.wait(60)
            print("Успешная авторизация!")
        except:
            print("Время вышло, запустите снова")
            await client.disconnect()
            return

    # --- блок сболра постов
    posts = []

    for channel in channels:
        messages = await client.get_messages(channel, limit=1)

        for message in messages:
            messageDate = message.date
            compareDate = datetime(2026, 2, 18, 17, 0, tzinfo=timezone.utc)

            if messageDate >= compareDate:
                if message.post and message.text:
                    posts.append({
                        "date": f"{messageDate}",
                        "channel": channel,
                        "channel_id": message.peer_id.channel_id,
                        "post_id": message.id,
                        "link": f"https://t.me/{channel}/{message.id}",
                        "content": message.text,
                    })

    # print(posts)
    # --- блок сболра постов

    # закрытие соединение после сбора данных
    await client.disconnect()

    return posts

posts = await main()

"""## AI обработка"""

# todo - пересмотреть минус слова
prompt = f"""Проанализируй контент каждого поста и верни json-коллекцию анонсов туристических мероприятий.

Анонсом туристического мероприятия можно считать контент, в котором есть информация о:
1. дате начала мероприятия;
2. время начала мероприятия;
3. время и дата больше текущего времени и даты.

Элемент коллекции должен иметь следующую структуру:
 - title - заголовок (название мероприятия),
 - description - краткое описание мероприятия,
 - date_start - дата начала мероприятия,
 - time_start - время начала мероприятия,
 - price_min - минимальная стоимость за участие в мероприятии (если о стоимости не говорится, то 0)
 - price_max - максимальная стоимость за участие в мероприятии (если о стоимости не говорится, то 0)
 - category - отнеси анонс к одной из категорий (походы, сплавы, экскурсии, спелео, восхождения, туры, соревнования, фото)
 - child - true - если в анонсе есть информация о том, что на мероприятие можно с детьми, false - если информации о детях нет

Оставь без изменения параметры:
 - channel;
 - channel_id;
 - post_id;
 - link.

Если пост не является анонсом, то переходи к обработке следующего элемента.

Пост не является анонсом если он представляет из себя:
 - информацию о предоставлении услуг(и);
 - отчёт о том, как прошло мероприятие;
 - отзыв о том, как прошло мероприятие;
 - иную информацию без указания даты и времени начала мероприятия.

Пост не является туристическим мероприятием если:
 - текст о мастер-классе;
 - текст о спектакле;
 - текст о культуре и посещении музеев;
 - текст о науке или рукоделии;
 - текст о встрече в квартире;
 - текст о нетворкинге;
 - текст о философии;
 - текст о церимонии;
 - текст о психологии;

Справка по категориям:
 - походы - не сложный маршрут, похожий на прогулку, может быть с подъёмом на гору, подготовка не требуется, традиционное мероприятие, обычно на один день или несколько часов;
 - восхождение - серьезное мероприятие, текст содержит упоминание о том, какая высота будет набрана и как называется гора (Аргыджэк, Борус и другие вершины), если такой информации нет, то это поход;
 - экскурсии - в тексте содержится слово экскурсия;
 - спелео - это спуски в пещеры;
 - туры - это мероприятие продолжительностью в несколько дней, смысл которого посетить новые места группой, часто на транспорте или заказном автобусе (тур по Алтаю, в Лесосибирск, тур на Иванвские озёра, путешествие в Тыву);
 - сплавы - в таком посте предлагается сплавиться по реке на сапах, байдарках, пакрафтах;
 - соревнования - в тексте фигурирует слово соревнования, а также обозначается их специфика;
 - фото - текст с акцентом на фотографию достопримечательностей, живописных мест или участников похода или прогулки.

Список постов:
{posts}"""
response = ai.generate_text(prompt, model_name='google/gemini-2.5-flash-lite')
print(response)

"""## Link parser"""

links = []

for channel in channels:
    messages = await client.get_messages(channel, limit=3000)

    for message in messages:

        url_pattern = r"https?://(?:[-\w.]|(?:%[\da-fA-F]{2}))+(?:/[-\w.%?=&#+]*)*"

        if message and message.text:

            found_urls = re.findall(url_pattern, message.text)

            for url in found_urls:

                if url.startswith("https://t.me/krasoutdoor") or url.startswith("https://vk.com") or url.startswith("https://vk.ru") or url.startswith("https://vk.cc"):
                    continue

                if url not in links:
                    links.append(url)

links.sort()

print(str(links))

"""## Структура ответа на метод `get_messages` (для постов)

```
{
  "messages": [
    {
      "_type": "Message",
      "id": 2075,
      "peer_id": {
        "_type": "PeerChannel",
        "channel_id": 1648212419
      },
      "date": "2026-02-05T06:00:22Z",
      "message": "🔹БИРЮСИНСКИЙ ЗАЛИВ\n(лёд Красноярского моря)                         \n\nБУДНИ \n10 февраля (вт) в 10.00\n11 февраля (ср) в 10.00\n12 февраля (чт) в 10.00\n13 февраля (пт) в 10.00\n\nВЫХОДНЫЕ\n14 февраля (сб) в 10.00                                 \n15 февраля (вс) в 10.00\n \n❄️Путешествие на Красноярское море в «Бирюсинский залив»\n\n🧊Мамонтова пещера\n🧊Царские ворота\n🧊Ущелье грот \n🔥Прожарка на костре \n\n❄️Поход по скальным объектам залива, пройдём в Мамонтову пещеру, поднимемся на Царские ворота! Посетим вертикальный  грот, прокатимся на качелях, покушаем в кемпинге с костром 🔥\n\n🚐Выезд: 10.00 Предмостная, Красный Яр. Матросова,4\nРасстояние – залив Шумиха 60км\nПитание: перекус-еда, чай-кофе!\nТеплая одежда, сидушка, ледоступы, гамаши, фонарик!\n****************************\n💗Участие: 2000р (доставка, сопровождение) \n\n®️Регистрация в личные\n\nгруппа в МАХ 📱\nгруппа в ВК 📱",
      "out": false,
      "mentioned": false,
      "media_unread": false,
      "silent": false,
      "post": true,
      "from_scheduled": false,
      "legacy": false,
      "edit_hide": false,
      "pinned": false,
      "noforwards": false,
      "invert_media": false,
      "offline": false,
      "video_processing_pending": false,
      "paid_suggested_post_stars": false,
      "paid_suggested_post_ton": false,
      "from_id": null,
      "from_boosts_applied": null,
      "saved_peer_id": null,
      "fwd_from": null,
      "via_bot_id": null,
      "via_business_bot_id": null,
      "reply_to": null,
      "media": {
        "_type": "MessageMediaDocument",
        "nopremium": false,
        "spoiler": false,
        "video": true,
        "round": false,
        "voice": false,
        "document": {
          "_type": "Document",
          "id": 5197512556805131270,
          "access_hash": -110495474101961571,
          "file_reference": "02623db9c30000081b6985f0710f5f9e2097e4e4c2e3cf678997006108",
          "date": "2026-02-05T06:00:22Z",
          "mime_type": "video/mp4",
          "size": 14316579,
          "dc_id": 2,
          "attributes": [
            {
              "_type": "DocumentAttributeVideo",
              "duration": 68.734001159668,
              "w": 848,
              "h": 448,
              "round_message": false,
              "supports_streaming": true,
              "nosound": false,
              "preload_prefix_size": null,
              "video_start_ts": null,
              "video_codec": null
            },
            {
              "_type": "DocumentAttributeFilename",
              "file_name": "IMG_3516.MOV"
            }
          ],
          "thumbs": [
            {
              "_type": "PhotoStrippedSize",
              "type": "i",
              "bytes": "0115289aea74b6f9442bcb920e3bf6a6c57ef22280ab903e6e2a4d454b59be3b60d47a74286db76ce5b3c93di8086f25c91b01c0cf4a44b86691dbe307e4c038ab66142c58asb76f5ed514f1ac568e428c85f5a684fc858c19d1491b403927d68a2c4936885ba9cff3a2902b8fb81be1e1653d0ff8d25a8d8b0228ec28a29813523a86054f4a28a403628c4518452481eb45145303f"
            },
            {
              "_type": "PhotoSize",
              "type": "m",
              "w": 320,
              "h": 169,
              "size": 14238
            }
          ],
          "video_thumbs": []
        },
        "alt_documents": [],
        "video_cover": null,
        "video_timestamp": null,
        "ttl_seconds": null
      },
      "reply_markup": null,
      "entities": [
        {
          "_type": "MessageEntityItalic",
          "offset": 20,
          "length": 49
        },
        {
          "_type": "MessageEntityBlockquote",
          "offset": 71,
          "length": 193,
          "collapsed": false
        },
        {
          "_type": "MessageEntityItalic",
          "offset": 71,
          "length": 10
        },
        {
          "_type": "MessageEntityItalic",
          "offset": 183,
          "length": 4
        },
        {
          "_type": "MessageEntityBold",
          "offset": 187,
          "length": 77
        },
        {
          "_type": "MessageEntityBold",
          "offset": 745,
          "length": 30
        },
        {
          "_type": "MessageEntityTextUrl",
          "offset": 844,
          "length": 15,
          "url": "https://max.ru/join/0m_s0bcYq41YLYxVKIvKMZKUvThQ4Uru0JLIKS5Dck0"
        },
        {
          "_type": "MessageEntityTextUrl",
          "offset": 860,
          "length": 11,
          "url": "https://vk.com/geoturizm?from=groups"
        },
        {
          "_type": "MessageEntityCustomEmoji",
          "offset": 872,
          "length": 2,
          "document_id": 5334853932915114338
        }
      ],
      "views": 471,
      "forwards": 6,
      "replies": {
        "_type": "MessageReplies",
        "replies": 19,
        "replies_pts": 42056,
        "comments": true,
        "recent_repliers": [
          {
            "_type": "PeerChannel",
            "channel_id": 1648212419
          },
          {
            "_type": "PeerUser",
            "user_id": 1930334798
          }
        ],
        "channel_id": 1803719418,
        "max_id": 25819,
        "read_max_id": null
      },
      "edit_date": "2026-02-05T07:51:36Z",
      "post_author": null,
      "grouped_id": null,
      "reactions": {
        "_type": "MessageReactions",
        "results": [
          {
            "_type": "ReactionCount",
            "reaction": {
              "_type": "ReactionEmoji",
              "emoticon": "🔥"
            },
            "count": 6,
            "chosen_order": null
          },
          {
            "_type": "ReactionCount",
            "reaction": {
              "_type": "ReactionEmoji",
              "emoticon": "👏"
            },
            "count": 4,
            "chosen_order": null
          },
          {
            "_type": "ReactionCount",
            "reaction": {
              "_type": "ReactionEmoji",
              "emoticon": "❤"
            },
            "count": 2,
            "chosen_order": null
          },
          {
            "_type": "ReactionCount",
            "reaction": {
              "_type": "ReactionEmoji",
              "emoticon": "💘"
            },
            "count": 2,
            "chosen_order": null
          }
        ],
        "min": false,
        "can_see_list": false,
        "reactions_as_tags": false,
        "recent_reactions": [],
        "top_reactors": []
      },
      "restriction_reason": [],
      "ttl_period": null,
      "quick_reply_shortcut_id": null,
      "effect": null,
      "factcheck": null,
      "report_delivery_until_date": null,
      "paid_message_stars": null,
      "suggested_post": null
    }
  ],
  "total": 1544
}
```

## Структура ответа `get_messages` (для фото)

```
{
  "id": 2070,
  "peer_id": {
    "channel_id": 1648212419,
    "_": "PeerChannel"
  },
  "date": "2026-02-02T06:49:41+00:00",
  "message": "",
  "out": false,
  "mentioned": false,
  "media_unread": false,
  "silent": false,
  "post": true,
  "from_scheduled": false,
  "legacy": false,
  "edit_hide": true,
  "pinned": false,
  "noforwards": false,
  "invert_media": false,
  "offline": false,
  "video_processing_pending": false,
  "paid_suggested_post_stars": false,
  "paid_suggested_post_ton": false,
  "from_id": null,
  "from_boosts_applied": null,
  "saved_peer_id": null,
  "fwd_from": null,
  "via_bot_id": null,
  "via_business_bot_id": null,
  "reply_to": null,
  "media": {
    "photo": {
      "id": 5188615931943391794,
      "access_hash": -8260592546971161773,
      "date": "2026-02-02T06:49:33+00:00",
      "sizes": [
        {
          "type": "i",
          "bytes": "AR4ov4Iy..."
        },
        {
          "type": "m",
          "w": 320,
          "h": 242,
          "size": 39875
        },
        {
          "type": "x",
          "w": 800,
          "h": 604,
          "size": 234666
        },
        {
          "type": "y",
          "w": 1195,
          "h": 902,
          "sizes": [
            16567,
            52876,
            109579,
            187771,
            339732
          ]
        }
      ],
      "dc_id": 2,
      "has_stickers": false
    },
    "_": "MessageMediaPhoto"
  },
  "reply_markup": null,
  "entities": [],
  "views": 533,
  "forwards": 16,
  "replies": null,
  "edit_date": "2026-02-02T06:49:44+00:00",
  "post_author": null,
  "grouped_id": 14160119848625890,
  "reactions": null,
  "restriction_reason": [],
  "ttl_period": null,
  "quick_reply_shortcut_id": null,
  "effect": null,
  "factcheck": null,
  "report_delivery_until_date": null,
  "paid_message_stars": null,
  "suggested_post": null
}
```

## TODO

1. Проанализировать возможность выгружать сообщения из чатов
"""